stages:
  - test
  - build
  - test2
  - stage dev
  - prod
  
install_env:
   stage: test
   script:
     - echo " test 1------------------------- "
   tags:
     - docker_in_docker
#     - stage-shell


run tests:
   stage: test
   script:
     - echo " test 2------------------------- "
   tags:
#     - stage-shell
     - docker_in_docker

linters:
   stage: test
   script:
     - echo " test linter--------------------- "
   tags:
#     - stage-shell
     - docker_in_docker

build:
   stage: build
   script:
     - echo 'running ./build.sh' 
#  when: manual
   tags:
     - docker_in_docker
#     - stage-shell

tests_after_build:
   stage: test2
   script:
     - echo " tests_after_build 1--------------------- "
   tags:
#     - stage-shell
     - docker_in_docker

deploy website:
   stage: stage dev
   script:
#     - mkdir /var/www/html
     - cp -rf ./HTML/* /var/HTML
     - echo 'running ./build.sh'
#   when: manual
   tags:
     - docker_in_docker
#     - stage-shell
   only:
     refs:
      - tags
      - master
      - /^release.*$/
      
    
deploy prod:
   stage: prod
   script:
      - echo 'running ./build.sh'
   when: manual
   tags:
     - docker_in_docker
#     - stage-shell
   only:
     refs:
      - tags
      - master
      - /^release.*$/

