stages:
  - test
  - build
  - test2
  - stage_dev
 # - prod
 # - backup
  
install_env:
  stage: test
  script:
    - echo " test 1------------------------- "
#  tags:
#    - stagshell     

#run tests:
#  stage: test
#  script:
#    - echo " test 2------------------------- "
#  tags:
#    - stagshel

#linters:
#  stage: test
#  script:
#    - echo " test linter--------------------- "
#  tags:
#    - stagshell

build:
  stage: build
  script:
    - echo 'running ./build.sh' 
  when: manual
#  tags:
#    - stagshell

tests_after_build:
   stage: test2
   script:
     - echo " tests_after_build 1--------------------- "
#   tags:
#     - stagshell

deploy website:
   stage: stage_dev
   script:
#     - mkdir /var/www
#     - mkdir /var/www/html
     - cp -rf ./html/* /var/www/html
     - echo "dev stage complite! ------#"
     - echo 'running ./build.sh'
#   when: manual
   tags:
     - stagshell
   only:
     refs:
      - tags
      - master
      - /^release.*$/
      
    
#deploy prod:
#   stage: prod
#   script:
#      - echo 'running ./build.sh'
#   when: manual
#   tags:
#     - stagshell
#   only:
#     refs:
#      - tags
#      - master
#      - /^release.*$/
      
#backup_site:
#  stage: backup
#  tags:
#    - stagshell
#  script:
#    - sudo tar --exclude /var/www/html/backup -cjvf /var/www/html/backup/site.bz2 /var/www/html 
#  only:
#    refs:
#      - tags
#      - master
#      - /^release.*$/      


