stages:
  - deploy
  - prod

deploy:
   stage: deploy
   script:
     - cp -rf ./html/* /var/www/html
#      - echo 'running ./build.sh'
#   when: manual
   tags:
     - stagshell
#   only:
#     refs:
#      - tags
#      - master
#      - /^release.*$/     
    
deploy prod:
   stage: prod
   script:
      - echo 'running ./build.sh'
   when: manual
   tags:
     - stagshell
   only:
     refs:
      - tags
      - master
      - /^release.*$/



