stages:
  - test
  - build
  - test2
  - stage dev
  - prod
  
install_env:
   stage: test
   script:
     - echo " test 1------------------------- "
   tags:
     - stagshell

run tests:
   stage: test
   script:
     - echo " test 2------------------------- "
   tags:
     - stagshell

linters:
   stage: test
   script:
     - echo " test linter--------------------- "
   tags:
     - stagshell

build:
   stage: build
   script:
     - echo 'running ./build.sh' 
#  when: manual
   tags:
     - stagshell

tests_after_build:
   stage: test2
   script:
     - echo " tests_after_build 1--------------------- "
   tags:
     - stagshell

deploy website:
   stage: stage dev
   script:
     - mkdir /var/www
     - mkdir /var/www/html
     - cp -rf ./html/* /var/www/html
     - echo 'running ./build.sh'
#   when: manual
   tags:
     - stagshell
   only:
     refs:
      - tags
      - master
      - /^release.*$/
      
    
deploy prod:
   stage: prod
   script:
      - echo 'running ./build.sh'
   when: manual
   tags:
     - stagshell
   only:
     refs:
      - tags
      - master
      - /^release.*$/

image: docker
services:
  - docker:bind 
before_script:
  - export 
  - docker login -u GiPhantom -p $CI_REGISTRY_PASSWORD
build:
  script:
    - docker build -t registry.gitlab.com/giphantom/skillbox_module1-lesson2 .
    - docker push registry.gitlab.com/giphantom/skillbox_module1-lesson2 